rootProject.name = "pabal"

include(
    "pabal-app",
    "pabal-common",
    "pabal-web",
    "pabal-security",
    "pabal-tenant-domain",
    "pabal-tenant-contract",
    "pabal-tenant-application",
    "pabal-tenant-api",
    "pabal-tenant-infrastructure",
    "pabal-workspace-domain",
    "pabal-workspace-contract",
    "pabal-workspace-application",
    "pabal-workspace-api",
    "pabal-workspace-infrastructure",
    "pabal-user-domain",
    "pabal-user-contract",
    "pabal-user-application",
    "pabal-user-api",
    "pabal-user-infrastructure",
    "pabal-messenger-domain",
    "pabal-messenger-application",
    "pabal-messenger-contract",
    "pabal-messenger-api",
    "pabal-messenger-infrastructure",
)
